# Generated by Django 3.1.4 on 2021-04-12 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30, null=True)),
                ('Apellidos', models.CharField(max_length=70, null=True)),
                ('Direccion', models.CharField(max_length=50, null=True)),
                ('Telefono', models.CharField(max_length=9, null=True)),
                ('FechaNacimiento', models.DateField(null=True, verbose_name='Fecha nacimiento')),
                ('Activado', models.BooleanField(default='True')),
                ('Clase', models.CharField(max_length=9, null=True)),
                ('Horario', models.CharField(max_length=20, null=True)),
                ('FechaUltimoExamen', models.DateField(null=True, verbose_name='Fecha ultimo examen')),
                ('kyu', models.CharField(max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.CharField(max_length=600, null=True)),
                ('Kyu', models.CharField(max_length=9, null=True)),
                ('Nombre', models.CharField(max_length=90, null=True)),
                ('Descripcion', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Go-no-sen'), (2, 'Go-shin'), (3, 'Agarres fundamentales'), (4, 'Katas'), (5, 'Kihon'), (6, 'Teoria'), (7, 'golpes'), (8, 'Caidas'), (9, 'Guardias'), (10, 'Extra')], default=1, null=True)),
                ('Orientacion', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Fronta'), (2, 'Lateral'), (3, 'Atras'), (4, '')], default=4, null=True)),
                ('Nombre', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30, null=True)),
                ('Apellidos', models.CharField(max_length=70, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParteExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Realizadas', models.IntegerField(null=True)),
                ('Nota', models.CharField(max_length=2, null=True)),
                ('Finalizada', models.BooleanField(default='False')),
                ('Info', models.CharField(max_length=200, null=True)),
                ('Alum', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.alumno')),
                ('Part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.parte')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='tur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.tutor'),
        ),
    ]
