# Generated by Django 3.1.7 on 2021-06-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_alumno_examenactivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parteexamen',
            name='Necesarias',
            field=models.IntegerField(default=1),
        ),
    ]
