# Generated by Django 3.1.7 on 2021-06-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_auto_20210608_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='CorreoElectronico',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='Dni',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='NumeroLicencia',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
