# Generated by Django 3.1.7 on 2021-06-15 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_auto_20210613_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialExamenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(null=True, verbose_name='Fecha finalización examen')),
                ('Kyu', models.CharField(max_length=9, null=True)),
                ('Alumno', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.alumno')),
            ],
        ),
    ]
