# Generated by Django 3.1.7 on 2021-06-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_historialexamenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='FechaInicioExamen',
            field=models.DateField(null=True, verbose_name='Fecha inicio examen'),
        ),
    ]
